/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-central-1",
    "aws_cognito_identity_pool_id": "eu-central-1:392df5ec-fd96-41a7-978d-f83cd003440b",
    "aws_cognito_region": "eu-central-1",
    "aws_user_pools_id": "eu-central-1_vWBRXtyXT",
    "aws_user_pools_web_client_id": "3qvomi6aaq40t7s12mg677r9ul",
    "oauth": {
        "domain": "rhinoglobal.auth.eu-central-1.amazoncognito.com",
        "scope": [
            "phone",
            "email",
            "openid",
            "profile",
            "aws.cognito.signin.user.admin"
        ],
        "redirectSignIn": "rhinoglobal://",
        "redirectSignOut": "rhinoglobal://",
        "responseType": "code",
    },
    "federationTarget": "COGNITO_USER_POOLS"
};


export default awsmobile;
