import vector from './vector.png';

export const topics = [
  {
    image: vector,
    color: '#747BC3',
    secondarycolor: '#82D2E9',
    title: 'Some card1',
  },
  {
    image: vector,
    color: '#747BC3',
    secondarycolor: '#82D2E9',
    title: 'Some card2',
  },
  {
    image: vector,
    color: '#747BC3',
    secondarycolor: '#82D2E9',
    title: 'Some card3',
  },
  {
    image: vector,
    color: '#747BC3',
    secondarycolor: '#82D2E9',
    title: 'Some card4',
  },
  {
    image: vector,
    color: '#747BC3',
    secondarycolor: '#82D2E9',
    title: 'Some card5',
  },
  {
    image: vector,
    color: '#747BC3',
    secondarycolor: '#82D2E9',
    title: 'Some card6',
  },
  {
    image: vector,
    color: '#747BC3',
    secondarycolor: '#82D2E9',
    title: 'Some card7',
  },
  {
    image: vector,
    color: '#747BC3',
    secondarycolor: '#82D2E9',
    title: 'Some card8',
  },
  {
    image: vector,
    color: '#747BC3',
    secondarycolor: '#82D2E9',
    title: 'Some card9',
  },
  {
    image: vector,
    color: '#747BC3',
    secondarycolor: '#82D2E9',
    title: 'Some card10',
  },
  {
    image: vector,
    color: '#747BC3',
    secondarycolor: '#82D2E9',
    title: 'Some card11',
  },
  {
    image: vector,
    color: '#747BC3',
    secondarycolor: '#82D2E9',
    title: 'Some card12',
  },
  {
    image: vector,
    color: '#747BC3',
    secondarycolor: '#82D2E9',
    title: 'Some card13',
  },
  {
    image: vector,
    color: '#747BC3',
    secondarycolor: '#82D2E9',
    title: 'Some card14',
  },
  {
    image: vector,
    color: '#747BC3',
    secondarycolor: '#82D2E9',
    title: 'Some card15',
  },
  {
    image: vector,
    color: '#747BC3',
    secondarycolor: '#82D2E9',
    title: 'Some card25',
  },
  {
    image: vector,
    color: '#747BC3',
    secondarycolor: '#82D2E9',
    title: 'Some card14',
  },
  {
    image: vector,
    color: '#747BC3',
    secondarycolor: '#82D2E9',
    title: 'Some card15',
  },
  {
    image: vector,
    color: '#747BC3',
    secondarycolor: '#82D2E9',
    title: 'Some card25',
  },
  {
    image: vector,
    color: '#747BC3',
    secondarycolor: '#82D2E9',
    title: 'Some card14',
  },
  {
    image: vector,
    color: '#747BC3',
    secondarycolor: '#82D2E9',
    title: 'Some card15',
  },
  {
    image: vector,
    color: '#747BC3',
    secondarycolor: '#82D2E9',
    title: 'Some card25',
  },
  {
    image: vector,
    color: '#747BC3',
    secondarycolor: '#82D2E9',
    title: 'Some card14',
  },
  {
    image: vector,
    color: '#747BC3',
    secondarycolor: '#82D2E9',
    title: 'Some card15',
  },
  {
    image: vector,
    color: '#747BC3',
    secondarycolor: '#82D2E9',
    title: 'Some card25',
  },
];
